export const IDEMPOTENCY_KEY_HEADER = 'Idempotency-Key';
export const MAX_IDEMPOTENCY_KEY_LENGTH = 255;

export const MISSING_IDEMPOTENCY_KEY_ERROR_CODE = 'MISSING_IDEMPOTENCY_KEY';
export const INVALID_IDEMPOTENCY_KEY_ERROR_CODE = 'INVALID_IDEMPOTENCY_KEY';
